
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Models.Produk;

import java.awt.Color;
import java.awt.Font;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class MainFrame extends javax.swing.JFrame {
    private int totalBelanja = 0;

    public MainFrame() {
        initComponents();
        tanggalNow();
        updateTable();
    }
    
    private void updateTable() {
        // Mendapatkan data dari database, misalnya dalam bentuk ArrayList<Produk> dengan menggunakan metode dari DbController
        List<Produk> produkList = DbController.getDatabase();

        // Menghapus data yang ada dalam tabel
        DefaultTableModel model = (DefaultTableModel) tableBarang.getModel();
        model.setRowCount(0);

        // Menambahkan data dari ArrayList<Produk> ke tabel
        for (Produk produk : produkList) {
            Object[] row = {produk.getId(), produk.getNama(), produk.getjumlah(), 0, produk.getHarga()};
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_tanggal = new javax.swing.JLabel();
        tf_tanggal = new javax.swing.JTextField();
        tf_customer = new javax.swing.JTextField();
        label_costumer = new javax.swing.JLabel();
        tf_kasir = new javax.swing.JTextField();
        label_kasir = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        label_produk = new javax.swing.JLabel();
        tf_produk = new javax.swing.JTextField();
        tf_stok = new javax.swing.JTextField();
        label_stok = new javax.swing.JLabel();
        label_harga = new javax.swing.JLabel();
        tf_harga = new javax.swing.JTextField();
        button_tambah = new javax.swing.JButton();
        button_edit = new javax.swing.JButton();
        button_hapus = new javax.swing.JButton();
        tf_id = new javax.swing.JTextField();
        label_id = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        label_total = new javax.swing.JLabel();
        show_total = new javax.swing.JLabel();
        label_statusBayar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        button_beli = new javax.swing.JButton();
        button_bayar = new javax.swing.JButton();
        label_tunai = new javax.swing.JLabel();
        tf_tunai = new javax.swing.JTextField();
        label_kembalian = new javax.swing.JLabel();
        tf_kembalian = new javax.swing.JTextField();
        button_batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("ROG Fonts", 0, 27)); // NOI18N
        jLabel1.setText("PILOSHOP");

        label_tanggal.setBackground(new java.awt.Color(204, 204, 204));
        label_tanggal.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label_tanggal.setText("TANGGAL");

        tf_tanggal.setEnabled(false);
        tf_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tanggalActionPerformed(evt);
            }
        });

        tf_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_customerActionPerformed(evt);
            }
        });

        label_costumer.setBackground(new java.awt.Color(204, 204, 204));
        label_costumer.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label_costumer.setText("CUSTOMER");

        tf_kasir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_kasir.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_kasir.setBackground(new java.awt.Color(204, 204, 204));
        label_kasir.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label_kasir.setText("KASIR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(tf_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(label_tanggal)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(label_costumer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(tf_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tf_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_kasir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_kasir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_costumer)
                            .addComponent(label_tanggal))))
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_produk.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label_produk.setText("PRODUK");

        tf_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_produkActionPerformed(evt);
            }
        });

        label_stok.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label_stok.setText("STOK");

        label_harga.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label_harga.setText("HARGA");

        button_tambah.setBackground(new java.awt.Color(204, 204, 255));
        button_tambah.setText("TAMBAH");
        button_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tambahActionPerformed(evt);
            }
        });

        button_edit.setBackground(new java.awt.Color(204, 204, 255));
        button_edit.setText("EDIT");
        button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editActionPerformed(evt);
            }
        });

        button_hapus.setBackground(new java.awt.Color(255, 0, 51));
        button_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button_hapus.setText("HAPUS");
        button_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hapusActionPerformed(evt);
            }
        });

        label_id.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        label_id.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(button_hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_tambah)
                .addGap(14, 14, 14))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_produk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_id, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_produk)
                    .addComponent(tf_stok)
                    .addComponent(tf_harga))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_produk)
                    .addComponent(tf_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_stok)
                    .addComponent(tf_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_harga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_tambah)
                    .addComponent(button_edit)
                    .addComponent(button_hapus))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setToolTipText("");

        label_total.setBackground(new java.awt.Color(204, 204, 255));
        label_total.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        label_total.setText("TOTAL");

        show_total.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        show_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        label_statusBayar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_statusBayar.setForeground(new java.awt.Color(0, 204, 51));
        label_statusBayar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_statusBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(show_total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(label_total)
                .addGap(0, 128, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(label_total, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_statusBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        tableBarang.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "PRODUK", "STOK", "JUMLAH", "HARGA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableBarang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tableBarangMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarang);
        if (tableBarang.getColumnModel().getColumnCount() > 0) {
            tableBarang.getColumnModel().getColumn(0).setMaxWidth(45);
            tableBarang.getColumnModel().getColumn(2).setMaxWidth(55);
            tableBarang.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        button_beli.setBackground(new java.awt.Color(102, 102, 255));
        button_beli.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        button_beli.setForeground(new java.awt.Color(255, 255, 255));
        button_beli.setText("BELI");
        button_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_beliActionPerformed(evt);
            }
        });

        button_bayar.setBackground(new java.awt.Color(102, 255, 102));
        button_bayar.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        button_bayar.setForeground(new java.awt.Color(255, 255, 255));
        button_bayar.setText("BAYAR");
        button_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bayarActionPerformed(evt);
            }
        });

        label_tunai.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        label_tunai.setText("TUNAI");

        label_kembalian.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        label_kembalian.setText("KEMBALIAN");

        tf_kembalian.setEnabled(false);

        button_batal.setBackground(new java.awt.Color(255, 0, 51));
        button_batal.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        button_batal.setForeground(new java.awt.Color(255, 255, 255));
        button_batal.setText("BATAL");
        button_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_kembalian)
                    .addComponent(label_tunai))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_tunai)
                    .addComponent(tf_kembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(button_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tunai)
                    .addComponent(tf_tunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_kembalian)
                    .addComponent(tf_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_bayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_beli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_batal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tanggalActionPerformed

    private List<Integer> selectedRowsList = new ArrayList<>();


    private void tanggalNow(){
                    // Mendapatkan tanggal saat ini
        LocalDate currentDate = LocalDate.now();

        // Format tanggal sesuai kebutuhan
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Mengubah tanggal menjadi string dalam format yang diinginkan
        String formattedDate = currentDate.format(dateFormatter);

        // Mengatur nilai tanggal ke field
        tf_tanggal.setText(formattedDate);
    }


private void button_beliActionPerformed(java.awt.event.ActionEvent evt) {
    int selectedRow = tableBarang.getSelectedRow();

    if (selectedRow != -1) {
        if (!selectedRowsList.contains(selectedRow)) {
            selectedRowsList.add(selectedRow);
        }

        int stockBarang = Integer.parseInt(tableBarang.getValueAt(selectedRow,2).toString());

        if (stockBarang > 0) {
            double hargaBarang = Double.parseDouble(tableBarang.getValueAt(selectedRow, 4).toString());
            totalBelanja += hargaBarang;
            show_total.setText(String.valueOf(totalBelanja));

            int jumlahBarang = Integer.parseInt(tableBarang.getValueAt(selectedRow, 3).toString());
            stockBarang--;
            jumlahBarang++;
            tableBarang.setValueAt(stockBarang, selectedRow, 2);
            tableBarang.setValueAt(jumlahBarang, selectedRow, 3);
        }
    }
}


    // private void button_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_beliActionPerformed
        // int selectedRow = tableBarang.getSelectedRow();

        // if (selectedRow != -1) {
        //     int stockBarang = Integer.parseInt(tableBarang.getValueAt(selectedRow, 2).toString());
            

        //     if (stockBarang > 0) {
        //         double hargaBarang = Double.parseDouble(tableBarang.getValueAt(selectedRow, 4).toString());
        //         totalBelanja += hargaBarang;
        //         show_total.setText(String.valueOf(totalBelanja));
                
        //         int jumlahBarang = Integer.parseInt(tableBarang.getValueAt(selectedRow, 3).toString());
        //         stockBarang--;
        //         jumlahBarang++;
        //         tableBarang.setValueAt(stockBarang, selectedRow, 2);
        //         tableBarang.setValueAt(jumlahBarang, selectedRow, 3);
                
        //     }

        // }

        
    // }//GEN-LAST:event_button_beliActionPerformed


    private void button_bayarActionPerformed(java.awt.event.ActionEvent evt) {
    DefaultTableModel model = (DefaultTableModel) tableBarang.getModel();
    String uangStr = tf_tunai.getText();
    String totalStr = show_total.getText();
    int uang = Integer.parseInt(uangStr);
    int total = Integer.parseInt(totalStr);

    for (int selectedRow : selectedRowsList) {
        int id = (int) model.getValueAt(selectedRow, 0);
        int stockBarang = (int) model.getValueAt(selectedRow, 2);

        if (stockBarang >= 0) {
            if (uang >= total) {
                DbController.updateJumlah(id, stockBarang);
                
                int kembalian = uang - total;
                String kembalianStr = String.valueOf(kembalian);
                tf_kembalian.setText(kembalianStr);
                label_statusBayar.setText("KEMBALIAN ANDA Rp." + tf_kembalian.getText());

                // Reset jumlah barang ke 0
                model.setValueAt(0, selectedRow, 3);
            } else {
                label_statusBayar.setForeground(Color.RED);
                label_statusBayar.setText("UANG ANDA TIDAK CUKUP!");
                updateTable();
            }
        }
    }

    // Reset total belanja ke 0
    totalBelanja = 0;
    tf_tunai.setText("");
    show_total.setText("0");
}



    // private void button_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bayarActionPerformed
    // int selectedRow = tableBarang.getSelectedRow();
    // String uangStr = tf_tunai.getText();
    // String totalStr = show_total.getText();
    // int uang = Integer.parseInt(uangStr);
    // int total = Integer.parseInt(totalStr);

    // if (selectedRow != -1) {
    //     DefaultTableModel model = (DefaultTableModel) tableBarang.getModel();

    //     int id = (int) model.getValueAt(selectedRow, 0);
    //     int stockBarang = (int) model.getValueAt(selectedRow, 2);

    //     if (stockBarang > 0) {
    //         if (uang >= total) {
    //             // Mengurangi stok barang di dalam tabel
    //             model.setValueAt(stockBarang, selectedRow, 2);

    //             // Update stok di database menggunakan DbController
    //             DbController.updateJumlah(id, stockBarang);
    //             label_statusBayar.setText("");
    //         } else {
    //             label_statusBayar.setText("Uang anda tidak cukup");
    //             updateTable();
    //         }
    //     }

//     DefaultTableModel model = (DefaultTableModel) tableBarang.getModel();
//     String uangStr = tf_tunai.getText();
//     String totalStr = show_total.getText();
//     int uang = Integer.parseInt(uangStr);
//     int total = Integer.parseInt(totalStr);

//     for (int selectedRow : selectedRowsList) {
//         int id = (int) model.getValueAt(selectedRow, 0);
//         int stockBarang = (int) model.getValueAt(selectedRow, 2);

//         if (stockBarang > 0) {
//             if (uang >= total) {
//                 DbController.updateJumlah(id, stockBarang);
//                 label_statusBayar.setText("");

//                 int kembalian = uang - total;
//                 String kembalianStr = String.valueOf(kembalian);
//                 tf_kembalian.setText(kembalianStr);
//      // Reset jumlah barang ke 0
//                 model.setValueAt(0, selectedRow, 3);
//             } else {
//                 label_statusBayar.setText("Uang anda tidak cukup");
//                 updateTable();
//             }
//         }
//     }

//     // Reset total belanja ke 0
//     totalBelanja = 0;
//     label_statusBayar.setText("0");

    

//     int kembalian = uang - total;
//     String kembalianStr = String.valueOf(kembalian);

//     // Reset jumlah barang ke 0
//     for (int row = 0; row < tableBarang.getRowCount(); row++) {
//         model = (DefaultTableModel) tableBarang.getModel();
//         model.setValueAt(0, row, 2);
//     }

//     // Reset total belanja ke 0
//     tf_kembalian.setText(kembalianStr);
//     totalBelanja = 0;
//     show_total.setText("0");


// }
        
//GEN-LAST:event_button_bayarActionPerformed

    private void button_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_batalActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableBarang.getSelectedRow();

        if (selectedRow != -1) {
            int stockBarang = Integer.parseInt(tableBarang.getValueAt(selectedRow, 2).toString());
            int jumlahBarang = Integer.parseInt(tableBarang.getValueAt(selectedRow, 3).toString());
            if (jumlahBarang > 0) {
                double hargaBarang = Double.parseDouble(tableBarang.getValueAt(selectedRow, 4).toString());
                totalBelanja -= hargaBarang;
                show_total.setText(String.valueOf(totalBelanja));
                
                stockBarang++;
                jumlahBarang--;
                tableBarang.setValueAt(stockBarang, selectedRow, 2);
                tableBarang.setValueAt(jumlahBarang, selectedRow, 3);

            
            }            
        }
    }//GEN-LAST:event_button_batalActionPerformed

    private void button_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tambahActionPerformed
        // TODO add your handling code here:
        String namaBaru = tf_produk.getText();
        String stokBarustr = tf_stok.getText();
        String hargaBarustr = tf_harga.getText();
        
        long hargaBaru = Long.parseLong(hargaBarustr);
        int stokBaru = Integer.parseInt(stokBarustr);
        DbController.insertData(namaBaru, hargaBaru, stokBaru);
        
        tf_produk.setText("");
        tf_stok.setText("");
        tf_harga.setText("");
        updateTable();
    }//GEN-LAST:event_button_tambahActionPerformed

    private void button_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hapusActionPerformed
        String target = tf_id.getText();
        
        int targetint = Integer.parseInt(target);
        DbController.deleteData(targetint);
       
        
        tf_id.setText("");
        updateTable();
    }//GEN-LAST:event_button_hapusActionPerformed

    private void button_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editActionPerformed
        String target = tf_id.getText();
        String namaBaru = tf_produk.getText();
        String stokBarustr = tf_stok.getText();
        String hargaBarustr = tf_harga.getText();
        
        long hargaBaru = Long.parseLong(hargaBarustr);
        int stokBaru = Integer.parseInt(stokBarustr);
        int targetint = Integer.parseInt(target);


        
        DbController.updateNama(targetint, namaBaru );
        DbController.updateJumlah(targetint, stokBaru);
        DbController.updateHarga(targetint, hargaBaru);
        
        tf_id.setText("");
        tf_produk.setText("");
        tf_stok.setText("");
        tf_harga.setText("");
        
        updateTable();

                

    }//GEN-LAST:event_button_editActionPerformed

    private void tf_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_produkActionPerformed

    private void tf_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_customerActionPerformed

    private void tableBarangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tableBarangMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_batal;
    private javax.swing.JButton button_bayar;
    private javax.swing.JButton button_beli;
    private javax.swing.JButton button_edit;
    private javax.swing.JButton button_hapus;
    private javax.swing.JButton button_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_costumer;
    private javax.swing.JLabel label_harga;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_kasir;
    private javax.swing.JLabel label_kembalian;
    private javax.swing.JLabel label_produk;
    private javax.swing.JLabel label_statusBayar;
    private javax.swing.JLabel label_stok;
    private javax.swing.JLabel label_tanggal;
    private javax.swing.JLabel label_total;
    private javax.swing.JLabel label_tunai;
    private javax.swing.JLabel show_total;
    private javax.swing.JTable tableBarang;
    private javax.swing.JTextField tf_customer;
    private javax.swing.JTextField tf_harga;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_kasir;
    private javax.swing.JTextField tf_kembalian;
    private javax.swing.JTextField tf_produk;
    private javax.swing.JTextField tf_stok;
    private javax.swing.JTextField tf_tanggal;
    private javax.swing.JTextField tf_tunai;
    // End of variables declaration//GEN-END:variables
}
